-- Add comprehensive USDA Rural Development programs with multilanguage support

INSERT INTO programs (title, title_es, title_zh, title_vi, description, description_es, description_zh, description_vi, url, category, eligibility, benefits, application_process, keywords) VALUES

-- Housing Programs
('Section 502 Guaranteed Loan Program',
'Programa de Préstamos Garantizados Sección 502',
'502节担保贷款计划',
'Chương trình Vay được Bảo lãnh Mục 502',
'Guarantees loans made by private lenders to low- and moderate-income rural homebuyers. No down payment required for qualified borrowers.',
'Garantiza préstamos otorgados por prestamistas privados a compradores de viviendas rurales de ingresos bajos y moderados. No se requiere pago inicial para prestatarios calificados.',
'为私人贷款人向低收入和中等收入农村购房者提供的贷款提供担保。合格借款人无需首付。',
'Bảo lãnh các khoản vay do người cho vay tư nhân cung cấp cho người mua nhà nông thôn có thu nhập thấp và trung bình. Không yêu cầu trả trước cho người vay đủ điều kiện.',
'https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-guaranteed-loan-program',
'Housing',
'Must have low to moderate income (up to 115% of area median income). Must be a U.S. citizen or qualified alien. Must be unable to obtain credit elsewhere. Property must be in eligible rural area. Must intend to occupy as primary residence.',
'No down payment required for qualified borrowers. 100% financing available. Lower mortgage insurance rates than FHA. 30-year fixed rate mortgages. Flexible credit guidelines. Can finance closing costs and repairs.',
'1. Find a USDA-approved lender. 2. Complete loan application with lender. 3. Provide income and credit documentation. 4. Property must meet USDA standards. 5. Lender submits to USDA for guarantee. 6. Closing and funding.',
ARRAY['housing', 'home loan', '502', 'guaranteed', 'no down payment', 'moderate income', 'purchase']),

('Section 521 Rental Assistance',
'Asistencia de Alquiler Sección 521',
'521节租金援助',
'Hỗ trợ Thuê nhà Mục 521',
'Provides payment assistance to low-income tenants living in USDA-financed rural rental housing. Reduces rent burden to 30% of adjusted income.',
'Proporciona asistencia de pago a inquilinos de bajos ingresos que viven en viviendas de alquiler rurales financiadas por el USDA. Reduce la carga del alquiler al 30% del ingreso ajustado.',
'为居住在USDA资助的农村租赁住房中的低收入租户提供付款援助。将租金负担降低到调整后收入的30%。',
'Cung cấp hỗ trợ thanh toán cho người thuê nhà có thu nhập thấp sống trong nhà cho thuê nông thôn được USDA tài trợ. Giảm gánh nặng tiền thuê xuống 30% thu nhập điều chỉnh.',
'https://www.rd.usda.gov/programs-services/multi-family-housing-programs/multi-family-housing-rental-assistance',
'Housing',
'Must be very low income (50% or less of area median income). Must live in a USDA Section 515 financed property. Property owner must participate in program. Priority for elderly, disabled, and families with children.',
'Reduces rent to 30% of adjusted monthly income. Long-term assistance (renewable annually). Helps prevent homelessness. Available for elderly, disabled, and families. Can combine with other assistance programs.',
'1. Contact property manager at USDA-financed property. 2. Complete rental application. 3. Provide income verification and household information. 4. Property manager submits assistance request. 5. Approval and assistance begins.',
ARRAY['housing', '521', 'rental assistance', 'rent subsidy', 'low income', 'affordable housing', 'tenant']),

('Housing Preservation Grants (HPG)',
'Subvenciones para la Preservación de Viviendas (HPG)',
'住房保护补助金（HPG）',
'Trợ cấp Bảo tồn Nhà ở (HPG)',
'Provides grants to sponsoring organizations to repair and rehabilitate housing for very low- and low-income rural homeowners and rental properties.',
'Proporciona subvenciones a organizaciones patrocinadoras para reparar y rehabilitar viviendas para propietarios rurales de ingresos muy bajos y bajos y propiedades de alquiler.',
'为赞助组织提供赠款，以修复和改造极低收入和低收入农村房主和租赁物业的住房。',
'Cung cấp trợ cấp cho các tổ chức tài trợ để sửa chữa và cải tạo nhà ở cho chủ nhà nông thôn có thu nhập rất thấp và thấp và tài sản cho thuê.',
'https://www.rd.usda.gov/programs-services/single-family-housing-programs/housing-preservation-grants',
'Housing',
'Applicants must be nonprofit organizations, state/local governments, or Indian tribes. Must serve very low- and low-income rural residents. Properties must be in eligible rural areas. Must demonstrate capacity to administer program.',
'Grants up to $25,000 per unit for repairs. Can serve homeowners and rental property owners. No repayment required. Covers health and safety repairs, accessibility improvements, and weatherization. Technical assistance available.',
'1. Nonprofit/government entity applies to USDA. 2. Submit organizational capacity and program plan. 3. Grant award. 4. Organization recruits eligible homeowners. 5. Conduct repairs with approved contractors. 6. Annual reporting.',
ARRAY['housing', 'preservation', 'grant', 'repair', 'rehabilitation', 'nonprofit', 'low income']),

('Farm Labor Housing Direct Loans',
'Préstamos Directos para Viviendas de Trabajadores Agrícolas',
'农场劳工住房直接贷款',
'Vay Trực tiếp Nhà ở Lao động Nông trại',
'Provides loans to farmers, family farm corporations, and nonprofit organizations to build, buy, improve or repair housing for domestic farm laborers.',
'Proporciona préstamos a agricultores, corporaciones agrícolas familiares y organizaciones sin fines de lucro para construir, comprar, mejorar o reparar viviendas para trabajadores agrícolas domésticos.',
'为农民、家庭农场公司和非营利组织提供贷款，用于为国内农场工人建造、购买、改善或修理住房。',
'Cung cấp các khoản vay cho nông dân, công ty trang trại gia đình và tổ chức phi lợi nhuận để xây dựng, mua, cải thiện hoặc sửa chữa nhà ở cho công nhân nông trại trong nước.',
'https://www.rd.usda.gov/programs-services/multi-family-housing-programs/farm-labor-housing-direct-loans-grants',
'Housing',
'Available to farmers, associations of farmers, family farm corporations, state/local governments, nonprofit organizations, and Indian tribes. Must provide housing for domestic farm labor. Must demonstrate need in area.',
'Loans up to 100% of development costs. 1% interest rate for nonprofits, 3% for others. 33-year loan terms. Can include space for dining facilities, recreation, and childcare. Low monthly payments.',
'1. Submit pre-application to USDA. 2. Site approval. 3. Detailed application with architectural plans. 4. Environmental review. 5. Loan approval. 6. Construction and occupancy.',
ARRAY['housing', 'farm labor', 'agricultural', 'workers', 'migrant', 'seasonal', 'nonprofit']),

('Mutual Self-Help Housing Technical Assistance',
'Asistencia Técnica para Viviendas de Autoayuda Mutua',
'互助自建住房技术援助',
'Hỗ trợ Kỹ thuật Nhà ở Tự giúp Tương hỗ',
'Provides grants to qualified nonprofit organizations and public bodies to help groups of very low- and low-income families build their own homes in rural areas.',
'Proporciona subvenciones a organizaciones sin fines de lucro calificadas y organismos públicos para ayudar a grupos de familias de ingresos muy bajos y bajos a construir sus propias casas en áreas rurales.',
'为合格的非营利组织和公共机构提供赠款，帮助极低收入和低收入家庭群体在农村地区建造自己的房屋。',
'Cung cấp trợ cấp cho các tổ chức phi lợi nhuận đủ điều kiện và các cơ quan công cộng để giúp các nhóm gia đình có thu nhập rất thấp và thấp xây dựng nhà riêng của họ ở các khu vực nông thôn.',
'https://www.rd.usda.gov/programs-services/single-family-housing-programs/mutual-self-help-housing-technical-assistance-grants',
'Housing',
'Applicants must be nonprofit organizations, state/local governments, or Indian tribes. Must have experience with self-help housing or construction. Families must be very low- or low-income. Must be in eligible rural area.',
'Grants to support staff and technical assistance. Families build equity through sweat equity. Reduces housing costs by 30-40%. Group approach builds community. Technical supervision provided. Can combine with Section 502 loans.',
'1. Organization applies for grant. 2. Grant award for technical assistance. 3. Recruit families. 4. Families apply for Section 502 loans. 5. Group construction with supervision. 6. Completion and occupancy.',
ARRAY['housing', 'self-help', 'mutual', 'construction', 'sweat equity', 'nonprofit', 'grant']),

-- Business Programs
('Rural Business Development Grants (RBDG)',
'Subvenciones para el Desarrollo de Negocios Rurales (RBDG)',
'农村商业发展补助金（RBDG）',
'Trợ cấp Phát triển Kinh doanh Nông thôn (RBDG)',
'Provides grants to support targeted technical assistance, training, and other activities leading to the development or expansion of small and emerging rural businesses.',
'Proporciona subvenciones para apoyar asistencia técnica dirigida, capacitación y otras actividades que conducen al desarrollo o expansión de pequeñas empresas rurales emergentes.',
'提供赠款以支持有针对性的技术援助、培训和其他活动，促进小型和新兴农村企业的发展或扩张。',
'Cung cấp trợ cấp để hỗ trợ hỗ trợ kỹ thuật có mục tiêu, đào tạo và các hoạt động khác dẫn đến phát triển hoặc mở rộng các doanh nghiệp nông thôn nhỏ và mới nổi.',
'https://www.rd.usda.gov/programs-services/business-programs/rural-business-development-grants',
'Business',
'Public bodies, nonprofits, Indian tribes, and cooperatives eligible. Must serve rural areas with 50,000 or fewer residents. Small and emerging businesses must be primary beneficiaries. Must demonstrate capacity.',
'Grants up to $500,000. Supports business training, technical assistance, feasibility studies, and business planning. Can fund equipment and facilities for job training. Helps entrepreneurs access capital and resources.',
'1. Review funding announcement. 2. Develop project plan for business development services. 3. Submit application during window. 4. USDA competitive review. 5. Grant award. 6. Implement activities and report.',
ARRAY['business', 'grant', 'development', 'training', 'technical assistance', 'small business', 'entrepreneurs']),

('Intermediary Relending Program (IRP)',
'Programa de Préstamos Intermediarios (IRP)',
'中介再贷款计划（IRP）',
'Chương trình Cho vay Trung gian (IRP)',
'Provides loans to intermediaries who establish revolving loan funds to provide financing to businesses for projects in rural areas.',
'Proporciona préstamos a intermediarios que establecen fondos de préstamos rotatorios para proporcionar financiamiento a empresas para proyectos en áreas rurales.',
'向中介机构提供贷款，由其建立循环贷款基金，为农村地区的项目提供商业融资。',
'Cung cấp các khoản vay cho các trung gian thiết lập quỹ vay luân chuyển để cung cấp tài chính cho các doanh nghiệp cho các dự án ở các khu vực nông thôn.',
'https://www.rd.usda.gov/programs-services/business-programs/intermediary-relending-program',
'Business',
'Intermediaries can be nonprofits, public agencies, Indian tribes, or cooperatives. Must have legal authority to borrow and lend. Must serve rural areas. Businesses receiving loans must create or save jobs.',
'USDA loans to intermediaries at 1% interest for 30 years. Intermediaries re-lend at their own rates. Flexible terms for end borrowers. Supports business creation, expansion, and retention. Revolving fund provides ongoing capital.',
'1. Intermediary applies to USDA for loan. 2. Submit lending plan and organizational capacity. 3. Loan approval and capitalization. 4. Intermediary lends to rural businesses. 5. Ongoing management and reporting.',
ARRAY['business', 'loan', 'intermediary', 'revolving fund', 'lending', 'jobs', 'rural development']),

('Value-Added Producer Grants (VAPG)',
'Subvenciones para Productores de Valor Agregado (VAPG)',
'增值生产者补助金（VAPG）',
'Trợ cấp Nhà sản xuất Giá trị Gia tăng (VAPG)',
'Helps agricultural producers enter value-added activities related to processing and marketing. Supports feasibility studies and working capital.',
'Ayuda a los productores agrícolas a participar en actividades de valor agregado relacionadas con el procesamiento y la comercialización. Apoya estudios de factibilidad y capital de trabajo.',
'帮助农业生产者进入与加工和营销相关的增值活动。支持可行性研究和营运资金。',
'Giúp các nhà sản xuất nông nghiệp tham gia vào các hoạt động giá trị gia tăng liên quan đến chế biến và tiếp thị. Hỗ trợ nghiên cứu khả thi và vốn lưu động.',
'https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants',
'Business',
'Independent agricultural producers, farmer/rancher cooperatives, agricultural producer groups, and majority-controlled producer-based businesses. Must add value to agricultural commodity. Priority for beginning, socially disadvantaged farmers.',
'Planning grants up to $75,000 for feasibility studies. Working capital grants up to $250,000. 50% matching funds required. Supports product development, marketing, and business planning. Creates new revenue streams.',
'1. Review funding announcement. 2. Develop value-added project plan. 3. Submit application with matching funds commitment. 4. Competitive review. 5. Grant award. 6. Implement project. 7. Report outcomes.',
ARRAY['business', 'agriculture', 'value-added', 'processing', 'marketing', 'grant', 'producers', 'farmers']),

('Rural Cooperative Development Grants',
'Subvenciones para el Desarrollo de Cooperativas Rurales',
'农村合作社发展补助金',
'Trợ cấp Phát triển Hợp tác xã Nông thôn',
'Funds centers that provide technical assistance to help rural residents form new cooperative businesses and improve operations of existing cooperatives.',
'Financia centros que brindan asistencia técnica para ayudar a los residentes rurales a formar nuevos negocios cooperativos y mejorar las operaciones de las cooperativas existentes.',
'资助中心提供技术援助，帮助农村居民组建新的合作企业并改善现有合作社的运营。',
'Tài trợ các trung tâm cung cấp hỗ trợ kỹ thuật để giúp cư dân nông thôn thành lập doanh nghiệp hợp tác xã mới và cải thiện hoạt động của các hợp tác xã hiện có.',
'https://www.rd.usda.gov/programs-services/business-programs/rural-cooperative-development-grants',
'Business',
'Nonprofits and institutions of higher education with cooperative development expertise. Must serve rural areas. Must provide technical assistance to cooperatives. Priority for underserved communities.',
'Grants up to $250,000 annually. Supports cooperative formation, strategic planning, governance, and marketing. Helps farmers and rural businesses increase market power. Creates jobs and economic opportunity.',
'1. Submit application showing cooperative development experience. 2. Describe technical assistance services to be provided. 3. Competitive review. 4. Grant award. 5. Provide assistance to cooperatives. 6. Annual reporting.',
ARRAY['business', 'cooperative', 'coop', 'development', 'technical assistance', 'grant', 'agriculture']),

-- Energy Programs
('Energy Efficiency and Conservation Loan Program (EECLP)',
'Programa de Préstamos para Eficiencia Energética y Conservación (EECLP)',
'能源效率和节能贷款计划（EECLP）',
'Chương trình Vay Hiệu quả Năng lượng và Bảo tồn (EECLP)',
'Provides zero-interest loans to electric utilities to implement energy efficiency and conservation programs for their customers.',
'Proporciona préstamos sin intereses a las empresas de servicios eléctricos para implementar programas de eficiencia energética y conservación para sus clientes.',
'为电力公司提供零利率贷款，以为其客户实施能源效率和节能计划。',
'Cung cấp các khoản vay lãi suất bằng không cho các công ty điện để thực hiện các chương trình hiệu quả năng lượng và bảo tồn cho khách hàng của họ.',
'https://www.rd.usda.gov/programs-services/electric-programs/energy-efficiency-conservation-loan-program',
'Energy',
'Electric utilities that are USDA Electric Program borrowers. Must serve rural areas. Programs must benefit residential, commercial, and industrial customers. Must result in measurable energy savings.',
'Zero-interest loans. 20-year terms. Can finance consumer loans for energy improvements. Supports insulation, HVAC upgrades, efficient appliances, LED lighting, and renewable energy. Reduces energy costs for rural customers.',
'1. Utility develops energy efficiency program plan. 2. Submit loan application to USDA. 3. Program approval. 4. Utility implements programs for customers. 5. Ongoing reporting on energy savings achieved.',
ARRAY['energy', 'efficiency', 'conservation', 'utility', 'electric', 'zero interest', 'savings']),

('Rural Energy Savings Program (RESP)',
'Programa de Ahorro de Energía Rural (RESP)',
'农村节能计划（RESP）',
'Chương trình Tiết kiệm Năng lượng Nông thôn (RESP)',
'Provides loans to electric utilities to make loans to customers for energy efficiency improvements and renewable energy systems.',
'Proporciona préstamos a las empresas de servicios eléctricos para otorgar préstamos a los clientes para mejoras de eficiencia energética y sistemas de energía renovable.',
'为电力公司提供贷款，以便向客户提供贷款，用于能源效率改进和可再生能源系统。',
'Cung cấp các khoản vay cho các công ty điện để cho khách hàng vay để cải thiện hiệu quả năng lượng và hệ thống năng lượng tái tạo.',
'https://www.rd.usda.gov/programs-services/electric-programs/rural-energy-savings-program',
'Energy',
'Electric utilities that serve rural areas. Utilities must be USDA borrowers or have USDA approval. End customers must be residential, commercial, or agricultural. Improvements must result in energy savings.',
'Loans up to $10,000 per customer. Long repayment periods (up to 10 years). Repayment through utility bill. No credit check for customers. Covers energy audits, insulation, HVAC, solar, and efficiency upgrades.',
'1. Utility applies for RESP loan from USDA. 2. Utility establishes customer loan program. 3. Customers apply through utility. 4. Energy assessment conducted. 5. Improvements installed. 6. Repayment via utility bill.',
ARRAY['energy', 'savings', 'efficiency', 'renewable', 'utility', 'on-bill', 'financing']),

-- Broadband/Telecommunications
('Community Connect Grant Program',
'Programa de Subvenciones Community Connect',
'社区连接补助金计划',
'Chương trình Trợ cấp Kết nối Cộng đồng',
'Provides grants for broadband deployment into rural communities where service does not exist. Must provide free access at community facility.',
'Proporciona subvenciones para el despliegue de banda ancha en comunidades rurales donde no existe servicio. Debe proporcionar acceso gratuito en una instalación comunitaria.',
'为农村社区提供宽带部署赠款，这些社区目前没有服务。必须在社区设施提供免费访问。',
'Cung cấp trợ cấp cho việc triển khai băng thông rộng vào các cộng đồng nông thôn nơi dịch vụ không tồn tại. Phải cung cấp quyền truy cập miễn phí tại cơ sở cộng đồng.',
'https://www.rd.usda.gov/programs-services/telecommunications-programs/community-connect-grants',
'Utilities',
'Legally organized entities including nonprofits, for-profits, tribes, cooperatives, and governments. Must serve area lacking broadband (less than 10 Mbps). Must provide free service to community facility for 2 years.',
'Grants up to $3 million. 100% grant (no matching required for economically challenged areas). Must provide at least 100 Mbps service. Covers construction, equipment, and network deployment. Builds community capacity.',
'1. Identify service area lacking broadband. 2. Partner with community facility. 3. Develop network design and budget. 4. Submit application during window. 5. Competitive review. 6. Award and deployment.',
ARRAY['broadband', 'internet', 'community', 'grant', 'rural connectivity', 'underserved', 'telecommunications']),

('Telecommunications Infrastructure Loans',
'Préstamos para Infraestructura de Telecomunicaciones',
'电信基础设施贷款',
'Vay Cơ sở hạ tầng Viễn thông',
'Provides loans for construction, improvement, and acquisition of telephone lines, facilities, and equipment in rural areas.',
'Proporciona préstamos para la construcción, mejora y adquisición de líneas telefónicas, instalaciones y equipos en áreas rurales.',
'为农村地区的电话线路、设施和设备的建设、改进和收购提供贷款。',
'Cung cấp các khoản vay cho xây dựng, cải tiến và mua lại đường dây điện thoại, cơ sở vật chất và thiết bị ở các khu vực nông thôn.',
'https://www.rd.usda.gov/programs-services/telecommunications-programs/telecommunications-infrastructure-loans-loan-guarantees',
'Utilities',
'Telecommunications providers including cooperatives, nonprofits, for-profit corporations, tribes, and municipalities. Must serve rural areas. Must demonstrate technical and financial feasibility.',
'Direct loans and loan guarantees. Long-term financing (up to 35 years). Competitive interest rates. Can finance fiber, wireless, satellite, and hybrid systems. Supports voice and broadband services.',
'1. Pre-application submission. 2. Feasibility study and engineering report. 3. Detailed application. 4. Financial and technical review. 5. Environmental assessment. 6. Loan approval and funding.',
ARRAY['telecommunications', 'phone', 'broadband', 'infrastructure', 'loan', 'rural', 'connectivity']),

-- Water and Waste Programs
('Emergency Community Water Assistance Grants',
'Subvenciones de Asistencia de Agua Comunitaria de Emergencia',
'紧急社区供水援助补助金',
'Trợ cấp Hỗ trợ Nước Cộng đồng Khẩn cấp',
'Provides grants to assist rural communities experiencing a significant decline in quantity or quality of drinking water or that have experienced a natural disaster.',
'Proporciona subvenciones para ayudar a las comunidades rurales que experimentan una disminución significativa en la cantidad o calidad del agua potable o que han experimentado un desastre natural.',
'为经历饮用水数量或质量显著下降或经历自然灾害的农村社区提供援助赠款。',
'Cung cấp trợ cấp để hỗ trợ các cộng đồng nông thôn đang trải qua sự suy giảm đáng kể về số lượng hoặc chất lượng nước uống hoặc đã trải qua thảm họa thiên nhiên.',
'https://www.rd.usda.gov/programs-services/water-environmental-programs/emergency-community-water-assistance-grants',
'Utilities',
'Public bodies, nonprofits, and federally recognized tribes serving rural areas with 10,000 or fewer residents. Must have significant decline in water supply or recent natural disaster. Emergency must pose health risk.',
'Grants up to $150,000 for water transmission lines, sources, or treatment. Up to $1 million for natural disasters. Can address water quantity or quality issues. Fast-track approval process. No matching required for emergencies.',
'1. Document emergency situation. 2. Contact state USDA office immediately. 3. Submit emergency application. 4. Expedited review. 5. Grant award. 6. Rapid implementation. 7. Resolution of emergency.',
ARRAY['water', 'emergency', 'disaster', 'grant', 'health', 'safety', 'drinking water', 'crisis']),

('Circuit Rider Program',
'Programa Circuit Rider',
'巡回服务计划',
'Chương trình Circuit Rider',
'Provides grants to nonprofits to hire and train circuit riders who provide technical assistance to small rural water systems.',
'Proporciona subvenciones a organizaciones sin fines de lucro para contratar y capacitar a trabajadores itinerantes que brindan asistencia técnica a pequeños sistemas de agua rurales.',
'为非营利组织提供赠款，以雇用和培训巡回服务人员，为小型农村供水系统提供技术援助。',
'Cung cấp trợ cấp cho các tổ chức phi lợi nhuận để thuê và đào tạo những người đi tuần tra cung cấp hỗ trợ kỹ thuật cho các hệ thống nước nông thôn nhỏ.',
'https://www.rd.usda.gov/programs-services/water-environmental-programs/circuit-rider-program',
'Utilities',
'Nonprofit organizations with experience providing technical assistance to water systems. Must serve multiple rural water systems. Priority for systems serving disadvantaged communities.',
'Multi-year grants to support circuit rider staff and expenses. Technical assistance improves system operations and compliance. Helps systems maintain infrastructure and meet regulations. Reduces operational costs.',
'1. Nonprofit applies for circuit rider grant. 2. Describe service area and systems to be served. 3. Grant award. 4. Hire and train circuit riders. 5. Provide ongoing technical assistance. 6. Annual reporting.',
ARRAY['water', 'technical assistance', 'circuit rider', 'operations', 'maintenance', 'training', 'small systems']),

('Solid Waste Management Grants',
'Subvenciones para la Gestión de Residuos Sólidos',
'固体废物管理补助金',
'Trợ cấp Quản lý Chất thải Rắn',
'Provides grants for solid waste management projects including recycling, landfill closure, and waste reduction programs in rural areas.',
'Proporciona subvenciones para proyectos de gestión de residuos sólidos, incluidos programas de reciclaje, cierre de vertederos y reducción de desechos en áreas rurales.',
'为农村地区的固体废物管理项目提供赠款，包括回收、垃圾填埋场关闭和减少废物计划。',
'Cung cấp trợ cấp cho các dự án quản lý chất thải rắn bao gồm tái chế, đóng cửa bãi rác và chương trình giảm thiểu chất thải ở các khu vực nông thôn.',
'https://www.rd.usda.gov/programs-services/water-environmental-programs/solid-waste-management-grants',
'Utilities',
'Public bodies, nonprofits, and federally recognized tribes in rural areas with 10,000 or fewer residents. Must address solid waste management needs. Priority for projects reducing environmental contamination.',
'Grants up to $100,000 for feasibility studies and technical assistance. Grants up to $1 million for construction. Supports recycling facilities, composting, and landfill improvements. 25-75% matching funds required.',
'1. Identify solid waste management need. 2. Conduct feasibility study. 3. Submit application. 4. Environmental review. 5. Grant approval. 6. Procurement and construction. 7. System operation.',
ARRAY['waste', 'solid waste', 'recycling', 'landfill', 'environment', 'grant', 'disposal']);
