INSERT INTO documents (title, description, document_url, document_type, category, language) VALUES
('B 1780-18', 'Daily Inspection Report', 'https://www.rd.usda.gov/media/file/download/uwp-rb-18.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-19', 'Water And Waste Letter Of Conditions', 'https://www.rd.usda.gov/media/file/download/uwp-rb-19.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-2', 'Preliminary Engineering Reports for the Water and Waste Disposal Program (4/4/13)', 'https://www.rd.usda.gov/media/file/download/uwp-bulletin-1780-2.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-20', 'Bylaws', 'https://www.rd.usda.gov/media/file/download/uwp-rb-20.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-22', 'Eligibility Certification', 'https://www.rd.usda.gov/media/file/download/uwp-rb-22.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-23', 'Project Management Agreement Between The Regional Commission and RUS', 'https://www.rd.usda.gov/media/file/download/uwp-rb-23.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-24', 'Public Works Assisted By An Agency Loan (EDA)', 'https://www.rd.usda.gov/media/file/download/uwp-rb-24.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-25', 'Construction of Public Works and Development Facilities (EDA)', 'https://www.rd.usda.gov/media/file/download/uwp-rb-25.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-26', 'Guidance for the Use of Engineers Joint Contract Documents Committee (EJCDC) Bidding and Contract Documents on Water and Waste Disposal Projects with Rural Utilities Service Financial Assistance (Revised 5/10/24)', 'https://www.rd.usda.gov/media/file/download/uwp-rb-26.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-27', 'Loan Resolution (Public Bodies)', 'https://www.rd.usda.gov/media/file/download/uwp-bulletin-1780-27.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-28', 'Loan Resolution Security Agreement (Revised 2-15-00)', 'https://www.rd.usda.gov/media/file/download/uwp-bulletin-1780-28.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-29', '2020 Poverty Guidelines (3-24-21)', 'https://www.rd.usda.gov/media/file/download/uwp-bulletin-1780-29.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-32', 'Memorandum of Agreement between the Appalachian Regional Commission and the Rural Utilities Service', 'https://www.rd.usda.gov/media/file/download/uwp-rb-32.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-33', 'Guidance for Conducting Value Engineering Studies for Water and Waste Projects (Effective 3-21-2005)', 'https://www.rd.usda.gov/media/file/download/uwp-valueengbulletin.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-34', 'Guidance for Using the Competitive Sealed Bids Process for the Water and Waste Disposal Program (Effective 9-5-2013)', 'https://www.rd.usda.gov/media/file/download/uwp-bulletin-1780-34.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-35', 'Guidance for the Implementation of American Iron and Steel (AIS) Requirements with Rural Utilities Service Financial Assistance (Effective 8-30-2017)', 'https://www.rd.usda.gov/media/file/download/uwp-bulletin-1780-35.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-6', 'Water And Waste Processing Checklist (Revised 8-7-2025)', 'https://www.rd.usda.gov/media/file/download/uwp-rb-06.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-7', 'Legal Services Agreement', 'https://www.rd.usda.gov/media/file/download/uwp-rb-07.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-8', 'Minimum Suggested Contents of Management Agreements', 'https://www.rd.usda.gov/media/file/download/uwp-rb-08.pdf', 'Bulletins', 'Utilities', 'en'),
('B 1780-9', 'Water Users Agreement', 'https://www.rd.usda.gov/media/file/download/uwp-rb-09.pdf', 'Bulletins', 'Utilities', 'en'),
('HB-1-3550 Direct Single Family Housing Loans and Grants - Field Office Handbook', 'Consolidated version (large document may take long to load)', 'https://www.rd.usda.gov/media/file/download/hb-1-3550-consolidated.pdf', 'Handbooks', 'Housing', 'en'),
('HB-1-3555 SFH Guaranteed Loan Program Technical Handbook', 'Consolidated version (large document may take long to load)', 'https://www.rd.usda.gov/media/file/download/hb-1-3555-consolidated.pdf', 'Handbooks', 'Housing', 'en'),
('HB-1-3560 MFH Loan Origination Handbook', 'Consolidated version (large document may take long to load)', 'https://www.rd.usda.gov/media/file/download/usda-rd-hb-1-3560-consolidated.pdf', 'Handbooks', 'Housing', 'en'),
('HB-1-3565 Guaranteed Rural Rental Housing Program Origination and Servicing Handbook', 'Table of Contents', 'https://www.rd.usda.gov/media/file/download/3565-1toc.pdf', 'Handbooks', 'Housing', 'en'),
('HB-2-3550 Direct Single Family Housing Loans and Grants - Servicing Office Handbook', 'Table of Contents', 'https://www.rd.usda.gov/media/file/download/3550-2toc.pdf', 'Handbooks', 'Housing', 'en'),
('HB-2-3560 MFH Asset Management Handbook', 'Consolidated version (large document may take long to load)', 'https://www.rd.usda.gov/media/file/download/usda-rd-hb-2-3560-consolidated.pdf', 'Handbooks', 'Housing', 'en'),
('HB-3-3560 MFH Project Servicing Handbook', 'Consolidated version (large document may take long to load)', 'https://www.rd.usda.gov/media/file/download/usda-rd-hb-3-3560-consolidated.pdf', 'Handbooks', 'Housing', 'en'),
('Multifamily Housing Rental Assistance Program', NULL, 'Provides rental assistance payments paid directly to the owners of USDA-financed Rural Rental or Farm Labor Housing projects on behalf of eligible tenants who cannot afford to pay their full rent', 'Program Matrix', 'General', 'en'),
('Multifamily Housing Tenant Voucher Program', NULL, 'Rent vouchers can be used to supplement rent payments at a former USDA-financed property, or at any nonsubsidized rental unit in the United States that meets USDA standards and agrees to accept the voucher', 'Program Matrix', 'General', 'en'),
('Off-Farm Labor Housing Direct Loans and Grants', NULL, 'Provides affordable financing to develop housing for farm workers. Funds can be used to buy or improve land, for new construction, to rehabilitate
existing rental housing in lower-income areas, or to purchase household furnishings.', 'Program Matrix', 'General', 'en'),
('Off-Farm Labor Housing Technical Assistance Grants', NULL, 'Provides funds for applicants of USDA RD Farm Labor Housing loans and grants.
Funds can be used to pay for technical assistance during the application process, loan
underwriting and closing, and to
offset certain transaction costs.', 'Program Matrix', 'General', 'en'),
('On-Farm Labor Housing Loans', NULL, 'Provides financing to develop
or rehabilitate rental housing for lower-income domestic, migrant, and seasonal farm laborers', 'Program Matrix', 'General', 'en'),
('Community Facilities Direct Loans,
Grants and Loan
Guarantees', NULL, 'Provides funds to improve, construct, develop, or finance essential community facilities for rural communities such
as hospitals, clinics, nursing homes, certain schools, child care centers, fire and rescue, public safety facilities, libraries, and town halls', 'Program Matrix', 'General', 'en'),
('Community Facilities Technical Assistance and Training Grants', NULL, 'Award grants to identify and plan for community facility needs. Grant funds can be used to identify public and private financial resources, prepare reports, surveys, and applications, and to improve the operational and financial management of existing community facilities', 'Program Matrix', 'General', 'en'),
('Rural Community Development Initiative Grants', NULL, 'Facilitates housing, community facilities, and community
and economic development projects. Grant funds can be used to support subgrantee trainings on homeownership or minority entrepreneur education, provide technical assistance on strategic plan development, help research and identify additional funding resources, prepare boards
of directors, and create training tools including videos, workbooks, or guides.', 'Program Matrix', 'General', 'en'),
('Tribal College Initiative Grants', NULL, 'Funds capital improvements to educational facilities and for cultural projects at 1994 Land Grant Institutions (Tribal Colleges). Funds can be used for infrastructure development or upgrades, along with equipment purchases for schools, libraries, and dormitories.', 'Program Matrix', 'General', 'en'),
('Agriculture Innovation Center Program', NULL, 'Funds technical assistance for agriculture innovation centers to develop and market value-added agricultural products. Funds can be used for center operations, development, marketing, financial or engineering services, and to connect producers to distribution and processing facilities.', 'Program Matrix', 'General', 'en'),
('BioPreferred Program', NULL, 'Helps provide new markets for farm commodities by increasing the purchase and use of biobased products.', 'Program Matrix', 'General', 'en'),
('Business and Industry Loan Guarantees', NULL, 'Provides loan guarantees to lenders for their loans  to eligible rural businesses and agricultural producers.
Funds can be used for real estate, buildings, equipment, supplies, working capital, and some debt refinancing.', 'Program Matrix', 'General', 'en'),
('Delta Health Care Services Grants', NULL, 'Provides financial assistance to address ongoing, unmet health needs in the Delta Region. Funds can be used to develop health care services, education, job training programs, and to develop or expand public health-related facilities in the region.', 'Program Matrix', 'General', 'en'),
('Strategic Economic and Community Development', NULL, 'Bolsters participating USDA Rural Development program funds by supporting projects that promote and implement strategic community investment plans. Funds can
be used to help amplify a rural community’s unique strengths, identify additional resources, convene partners, and leverage other federal, state, local, and private funding.', 'Program Matrix', 'General', 'en'),
('Value-Added Producer Grants', NULL, 'Helps independent agricultural producers begin processing and marketing activities that add value to their products. Grant and matching funds can be used for planning activities and working capital expenses related to producing
and marketing a value-added agricultural product. Examples include conducting feasibility studies, developing business plans, offsetting processing costs, handling marketing and advertising expenses, and paying certain inventory and salary expenses.', 'Program Matrix', 'General', 'en'),
('Community Facilities Direct Loans & Grants', 'https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-direct-loan-grant-program', 'This program provides affordable funding to develop essential community facilities in rural areas. An essential community facility is defined as a facility that provides an essential service to the local community for the orderly development of the community in a primarily rural area, and does not include private, commercial or business undertakings.', 'Programs & Services', 'General', 'en'),
('Community Facilities Loan Guarantees', 'https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-guaranteed-loan-program', 'This program provides loan guarantees to eligible lenders to develop essential community facilities in rural areas. An essential community facility is defined as a public improvement, operated on a non-profit basis, needed for the orderly development of a rural community where the rural community is a city or town, or its equivalent county or multi-county area.  The term “facility” refers to both the physical structure financed, and the resulting service provided to rural residents or rural busi', 'Programs & Services', 'General', 'en'),
('Community Facilities Technical Assistance and Training Grant', 'https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-technical-assistance-and-training-grant', 'This program provides technical assistance and training grants to eligible public bodies and private, nonprofit organizations (such as states, counties, cities, townships, incorporated towns, villages, boroughs, authorities, districts, and Tribes located on Federal or state reservations) to provide technical assistance and/or training in support of essential community facilities programs.', 'Programs & Services', 'General', 'en'),
('Rural Community Development Initiative Grants', 'https://www.rd.usda.gov/programs-services/community-facilities/rural-community-development-initiative-grants', 'RCDI grants are awarded to help non-profit housing and community development organizations, low-income rural communities and federally recognized tribes support housing, community facilities and community and economic development projects in rural areas.', 'Programs & Services', 'General', 'en'),
('Tribal College Initiative Grants', 'https://www.rd.usda.gov/programs-services/community-facilities/tribal-college-initiative-grants', 'This program provides funding to 1994 Land Grant Institutions (Tribal Colleges) to make capital improvements to their educational facilities and to purchase equipment.', 'Programs & Services', 'General', 'en'),
('Denali Commission High Energy Cost Grants', 'https://www.rd.usda.gov/programs-services/electric-programs/denali-commission-high-energy-cost-grants', 'This program assists the Denali Commission in lowering the cost of energy for families and individuals in areas with extremely high per-household energy costs (275% of the national average or higher).', 'Programs & Services', 'General', 'en'),
('Distributed Generation Energy Project Financing', 'https://www.rd.usda.gov/programs-services/electric-programs/distributed-generation-energy-project-financing', 'This program can provide loans and loan guarantees to energy project developers for distributed energy projects including renewables that provide wholesale or retail electricity to existing Electric Program borrowers or to rural communities served by other utilities.', 'Programs & Services', 'General', 'en'),
('Electric Infrastructure Loan & Loan Guarantee Program', 'https://www.rd.usda.gov/programs-services/electric-programs/electric-infrastructure-loan-loan-guarantee-program', 'This program makes insured loans and loan guarantees to nonprofit and cooperative associations, public bodies, and other utilities. Insured loans primarily finance the construction of electric distribution facilities in rural areas.', 'Programs & Services', 'General', 'en');