-- Import comprehensive USDA Rural Development programs with multilanguage support

INSERT INTO programs (title, title_es, title_zh, title_vi, description, description_es, description_zh, description_vi, url, category, eligibility, benefits, application_process, keywords) VALUES

('Section 502 Direct Loan Program',
'Programa de Préstamos Directos Sección 502',
'502节直接贷款计划',
'Chương trình Vay trực tiếp Mục 502',
'Provides low-interest loans to low and very-low income applicants to purchase, build, repair, renovate or relocate a home in eligible rural areas.',
'Proporciona préstamos de bajo interés a solicitantes de ingresos bajos y muy bajos para comprar, construir, reparar, renovar o reubicar una vivienda en áreas rurales elegibles.',
'为低收入和极低收入申请人提供低息贷款，用于在符合条件的农村地区购买、建造、修理、翻新或搬迁房屋。',
'Cung cấp các khoản vay lãi suất thấp cho người nộp đơn có thu nhập thấp và rất thấp để mua, xây dựng, sửa chữa, cải tạo hoặc di chuyển nhà ở các khu vực nông thôn đủ điều kiện.',
'https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-direct-home-loans',
'Housing',
'Must be a U.S. citizen, U.S. non-citizen national, or qualified alien. Must have low or very low income (typically 50-80% of area median income). Must be unable to obtain conventional credit. Property must be located in an eligible rural area. Must demonstrate repayment ability.',
'Low fixed interest rates (as low as 1%). No down payment required for qualified applicants. 100% financing available. 30 or 33-year terms. Payment assistance available through subsidy programs.',
'1. Contact your local USDA Rural Development office. 2. Complete a pre-application to determine eligibility. 3. Gather required documentation (proof of income, credit history, employment verification). 4. Submit formal application. 5. Property appraisal and inspection. 6. Loan closing and funding.',
ARRAY['housing', 'home loan', '502', 'direct loan', 'low income', 'rural housing', 'purchase', 'build']),

('Section 504 Home Repair Loans and Grants',
'Préstamos y Subvenciones para Reparación de Viviendas Sección 504',
'504节房屋维修贷款和补助金',
'Vay và Trợ cấp Sửa chữa Nhà Mục 504',
'Provides loans and grants to very-low-income homeowners to repair, improve or modernize their homes or to remove health and safety hazards.',
'Proporciona préstamos y subvenciones a propietarios de viviendas de ingresos muy bajos para reparar, mejorar o modernizar sus hogares o para eliminar peligros para la salud y la seguridad.',
'为极低收入房主提供贷款和补助金，用于修理、改善或现代化他们的房屋或消除健康和安全隐患。',
'Cung cấp các khoản vay và trợ cấp cho chủ nhà có thu nhập rất thấp để sửa chữa, cải thiện hoặc hiện đại hóa nhà của họ hoặc loại bỏ các mối nguy hiểm về sức khỏe và an toàn.',
'https://www.rd.usda.gov/programs-services/single-family-housing-programs/single-family-housing-repair-loans-grants',
'Housing',
'Must be very low income (50% or less of area median income). Must own and occupy the property. Property must be in eligible rural area. For grants: Must be 62 years or older and unable to repay a loan.',
'Loans up to $40,000 at 1% interest for 20 years. Grants up to $10,000 for seniors 62+. Can combine loan and grant (up to $50,000 total). No monthly payments during active agricultural season for farmer applicants.',
'1. Contact local USDA Rural Development office. 2. Submit application with income documentation. 3. Property inspection to identify needed repairs. 4. Approval and fund disbursement. 5. Complete repairs with approved contractors.',
ARRAY['housing', 'repair', '504', 'grant', 'loan', 'seniors', 'home improvement', 'very low income']),

('Section 515 Rural Rental Housing Loans',
'Préstamos para Viviendas de Alquiler Rurales Sección 515',
'515节农村租赁住房贷款',
'Vay Nhà cho thuê Nông thôn Mục 515',
'Provides loans to develop affordable multi-family rental housing for very low-, low-, and moderate-income families; the elderly; and persons with disabilities in eligible rural areas.',
'Proporciona préstamos para desarrollar viviendas de alquiler multifamiliares asequibles para familias de ingresos muy bajos, bajos y moderados; personas mayores; y personas con discapacidades en áreas rurales elegibles.',
'提供贷款用于为极低收入、低收入和中等收入家庭、老年人和残疾人在符合条件的农村地区开发负担得起的多户租赁住房。',
'Cung cấp các khoản vay để phát triển nhà cho thuê đa gia đình giá cả phải chăng cho các gia đình có thu nhập rất thấp, thấp và trung bình; người cao tuổi; và người khuyết tật ở các khu vực nông thôn đủ điều kiện.',
'https://www.rd.usda.gov/programs-services/multi-family-housing-programs/multi-family-housing-direct-loans',
'Housing',
'Available to individuals, trusts, associations, partnerships, limited partnerships, State or local public agencies, consumer cooperatives, and profit or nonprofit corporations. Must serve very low-, low-, and moderate-income families in rural areas. Property must remain affordable for at least 20 years.',
'Direct loans up to 100% of development costs. 50-year terms. 1% interest rate. No prepayment penalty after 20 years. Can be combined with Low-Income Housing Tax Credits and other financing.',
'1. Pre-application submission. 2. Site review and approval. 3. Detailed application with architectural plans. 4. Environmental review. 5. Loan approval and closing. 6. Construction and inspection. 7. Final disbursement.',
ARRAY['housing', '515', 'rental', 'multi-family', 'apartment', 'affordable housing', 'developers', 'nonprofits']),

('Business & Industry (B&I) Loan Guarantee Program',
'Programa de Garantía de Préstamos para Negocios e Industria (B&I)',
'商业与工业（B&I）贷款担保计划',
'Chương trình Bảo lãnh Vay Kinh doanh & Công nghiệp (B&I)',
'Provides loan guarantees to lenders to develop or finance business and industry in rural areas. Supports job creation, retention, and economic development.',
'Proporciona garantías de préstamos a prestamistas para desarrollar o financiar negocios e industrias en áreas rurales. Apoya la creación de empleos, la retención y el desarrollo económico.',
'为贷款人提供贷款担保，以在农村地区发展或融资企业和工业。支持创造就业、保留就业和经济发展。',
'Cung cấp bảo lãnh vay cho người cho vay để phát triển hoặc tài trợ kinh doanh và công nghiệp ở các khu vực nông thôn. Hỗ trợ tạo việc làm, duy trì và phát triển kinh tế.',
'https://www.rd.usda.gov/programs-services/business-programs/business-industry-loan-guarantees',
'Business',
'Must be a legally organized entity. Must be located in eligible rural area (generally communities of 50,000 or less). Must demonstrate feasibility and create or save jobs. For-profit businesses, cooperatives, Indian tribes, and public bodies eligible.',
'Loan guarantees up to $25 million (80% for loans up to $5M, 70% for loans $5-10M, 60% for loans over $10M). Can finance working capital, equipment, real estate, and business acquisition. Long-term financing available. Competitive interest rates.',
'1. Work with an approved lender to prepare application. 2. Submit application to USDA including business plan and financial projections. 3. USDA review and environmental assessment. 4. Conditional commitment issued. 5. Final loan closing with lender. 6. Begin operations.',
ARRAY['business', 'b&i', 'loan guarantee', 'financing', 'economic development', 'rural business', 'manufacturing', 'processing']),

('Rural Energy for America Program (REAP)',
'Programa de Energía Rural para América (REAP)',
'美国农村能源计划（REAP）',
'Chương trình Năng lượng Nông thôn cho Mỹ (REAP)',
'Provides guaranteed loan financing and grant funding to agricultural producers and rural small businesses for renewable energy systems and energy efficiency improvements.',
'Proporciona financiamiento de préstamos garantizados y fondos de subvención a productores agrícolas y pequeñas empresas rurales para sistemas de energía renovable y mejoras de eficiencia energética.',
'为农业生产者和农村小企业提供可再生能源系统和能源效率改进的担保贷款融资和赠款资金。',
'Cung cấp tài trợ vay được bảo lãnh và quỹ trợ cấp cho các nhà sản xuất nông nghiệp và doanh nghiệp nhỏ nông thôn cho các hệ thống năng lượng tái tạo và cải thiện hiệu quả năng lượng.',
'https://www.rd.usda.gov/programs-services/energy-programs/rural-energy-america-program-renewable-energy-systems-energy-efficiency-improvement-guaranteed-loans',
'Energy',
'Agricultural producers with at least 50% gross income from agricultural operations. Rural small businesses in eligible rural areas. Must demonstrate technical and economic feasibility.',
'Grants up to 25% of total eligible project costs (maximum $500,000 for renewable energy, $250,000 for energy efficiency). Loan guarantees up to $25 million. Can combine grant and loan guarantee. Covers solar, wind, biomass, geothermal, hydropower, and energy efficiency projects.',
'1. Conduct energy audit or renewable energy assessment. 2. Complete feasibility study. 3. Submit application during open application window. 4. USDA competitive review and scoring. 5. Award notification. 6. Project implementation and verification.',
ARRAY['energy', 'reap', 'renewable', 'solar', 'wind', 'biomass', 'energy efficiency', 'grant', 'agricultural']),

('ReConnect Program',
'Programa ReConnect',
'ReConnect计划',
'Chương trình ReConnect',
'Provides loans, grants, and loan/grant combinations to facilitate broadband deployment in rural areas that currently lack sufficient access to broadband.',
'Proporciona préstamos, subvenciones y combinaciones de préstamos/subvenciones para facilitar el despliegue de banda ancha en áreas rurales que actualmente carecen de acceso suficiente a banda ancha.',
'提供贷款、赠款和贷款/赠款组合，以促进在目前缺乏足够宽带接入的农村地区部署宽带。',
'Cung cấp các khoản vay, trợ cấp và kết hợp vay/trợ cấp để tạo điều kiện triển khai băng thông rộng ở các khu vực nông thôn hiện thiếu quyền truy cập băng thông rộng đầy đủ.',
'https://www.rd.usda.gov/programs-services/telecommunications-programs/reconnect-program',
'Utilities',
'Legally organized entities including cooperatives, nonprofits, for-profit corporations, tribes, and state/local governments. Must serve areas with less than 100 Mbps download/20 Mbps upload speeds. Must provide at least 100/100 Mbps symmetrical service.',
'100% grants up to $35 million for extremely underserved areas. 50/50 loan/grant combinations. 100% loans with favorable terms. Covers construction, improvement, and acquisition of broadband infrastructure. Priority for areas with no existing broadband.',
'1. Review Funding Opportunity Announcement (FOA). 2. Determine service area eligibility. 3. Prepare detailed application with network design. 4. Submit during application window. 5. USDA review and scoring. 6. Award announcement. 7. Environmental review. 8. Construction and deployment.',
ARRAY['broadband', 'reconnect', 'internet', 'fiber', 'rural connectivity', 'telecommunications', 'high-speed internet']),

('Water & Waste Disposal Loan & Grant Program',
'Programa de Préstamos y Subvenciones para Agua y Eliminación de Desechos',
'水和废物处理贷款和补助金计划',
'Chương trình Vay và Trợ cấp Nước & Xử lý Chất thải',
'Provides funding to develop water and wastewater systems in rural communities with 10,000 or fewer residents. Helps ensure clean, reliable drinking water systems and sanitary waste disposal.',
'Proporciona financiamiento para desarrollar sistemas de agua y aguas residuales en comunidades rurales con 10,000 o menos residentes. Ayuda a garantizar sistemas de agua potable limpios y confiables y la eliminación sanitaria de desechos.',
'为拥有10,000名或更少居民的农村社区开发供水和废水系统提供资金。帮助确保清洁、可靠的饮用水系统和卫生废物处理。',
'Cung cấp tài trợ để phát triển hệ thống nước và nước thải ở các cộng đồng nông thôn có 10.000 cư dân trở xuống. Giúp đảm bảo hệ thống nước uống sạch, đáng tin cậy và xử lý chất thải vệ sinh.',
'https://www.rd.usda.gov/programs-services/water-environmental-programs/water-waste-disposal-loan-grant-program',
'Utilities',
'Public bodies, nonprofits, and federally recognized tribes. Must serve rural areas with 10,000 or fewer residents. Must demonstrate need and financial capacity. Priority to communities with health and sanitary problems.',
'Loans up to the full development cost. Grants based on median household income and project costs. Can combine loans and grants. Long-term financing (up to 40 years). Low interest rates. Covers construction, improvements, and acquisitions of water/waste systems.',
'1. Contact state USDA Rural Development office. 2. Pre-application submission. 3. Preliminary engineering report. 4. Full application with environmental review. 5. Loan/grant approval. 6. Procurement and construction. 7. Project completion and closeout.',
ARRAY['water', 'wastewater', 'waste disposal', 'sewer', 'infrastructure', 'drinking water', 'sanitation', 'rural utilities']),

('Community Facilities Direct Loan & Grant Program',
'Programa de Préstamos y Subvenciones Directas para Instalaciones Comunitarias',
'社区设施直接贷款和补助金计划',
'Chương trình Vay trực tiếp và Trợ cấp Cơ sở vật chất Cộng đồng',
'Provides funding to develop essential community facilities in rural areas including healthcare clinics, schools, libraries, childcare centers, fire stations, and community centers.',
'Proporciona financiamiento para desarrollar instalaciones comunitarias esenciales en áreas rurales, incluidas clínicas de salud, escuelas, bibliotecas, centros de cuidado infantil, estaciones de bomberos y centros comunitarios.',
'提供资金用于在农村地区开发基本社区设施，包括医疗诊所、学校、图书馆、托儿中心、消防站和社区中心。',
'Cung cấp tài trợ để phát triển các cơ sở vật chất cộng đồng thiết yếu ở các khu vực nông thôn bao gồm phòng khám y tế, trường học, thư viện, trung tâm chăm sóc trẻ em, trạm cứu hỏa và trung tâm cộng đồng.',
'https://www.rd.usda.gov/programs-services/community-facilities/community-facilities-direct-loan-grant-program',
'Community Facilities',
'Public bodies, community-based nonprofits, and federally recognized tribes. Must serve rural areas with 20,000 or fewer residents. Must demonstrate need, feasibility, and financial capacity.',
'Loans up to full project cost with up to 40-year terms. Grants available based on community need and income levels. Can combine loans and grants. Covers construction, enlargement, equipment, and land acquisition for essential community facilities.',
'1. Determine project feasibility and community need. 2. Contact state USDA office. 3. Pre-application submission. 4. Full application with architectural plans and budget. 5. Environmental and historical review. 6. Loan/grant approval. 7. Construction and inspections. 8. Project completion.',
ARRAY['community facilities', 'healthcare', 'school', 'library', 'fire station', 'childcare', 'public safety', 'rural infrastructure']),

('Rural Microentrepreneur Assistance Program (RMAP)',
'Programa de Asistencia para Microempresarios Rurales (RMAP)',
'农村微型企业家援助计划（RMAP）',
'Chương trình Hỗ trợ Nhà doanh nghiệp Nhỏ Nông thôn (RMAP)',
'Provides loans and grants to support the development of rural microenterprises and microentrepreneurs. Helps create rural jobs and economic opportunities.',
'Proporciona préstamos y subvenciones para apoyar el desarrollo de microempresas y microempresarios rurales. Ayuda a crear empleos rurales y oportunidades económicas.',
'提供贷款和赠款以支持农村微型企业和微型企业家的发展。帮助创造农村就业机会和经济机会。',
'Cung cấp các khoản vay và trợ cấp để hỗ trợ phát triển các doanh nghiệp nhỏ nông thôn và nhà doanh nghiệp nhỏ. Giúp tạo việc làm nông thôn và cơ hội kinh tế.',
'https://www.rd.usda.gov/programs-services/business-programs/rural-microentrepreneur-assistance-program',
'Business',
'Rural microenterprises with 10 or fewer employees. Microenterprise Development Organizations (MDOs) to provide technical assistance and loans. Must be located in rural areas. Startups and existing businesses eligible.',
'Direct microloans up to $50,000 to microenterprises. Grants to MDOs to establish revolving loan funds and provide training/technical assistance. Low interest rates. Flexible terms. Technical assistance available.',
'Microenterprises: 1. Contact participating MDO. 2. Develop business plan. 3. Apply through MDO. 4. Receive technical assistance. 5. Loan closing and funding. MDOs: 1. Submit grant application to USDA. 2. Demonstrate capacity. 3. Award and establish program. 4. Provide loans and technical assistance.',
ARRAY['microenterprise', 'small business', 'startup', 'entrepreneur', 'microloan', 'rural jobs', 'business development']),

('Distance Learning and Telemedicine (DLT) Grants',
'Subvenciones para Aprendizaje a Distancia y Telemedicina (DLT)',
'远程学习和远程医疗（DLT）补助金',
'Trợ cấp Học từ xa và Y học từ xa (DLT)',
'Provides financial assistance to help rural communities use telecommunications technology to connect to each other and to the world for educational and medical purposes.',
'Proporciona asistencia financiera para ayudar a las comunidades rurales a utilizar tecnología de telecomunicaciones para conectarse entre sí y con el mundo con fines educativos y médicos.',
'提供财政援助，帮助农村社区使用电信技术相互连接并连接世界以实现教育和医疗目的。',
'Cung cấp hỗ trợ tài chính để giúp các cộng đồng nông thôn sử dụng công nghệ viễn thông để kết nối với nhau và với thế giới cho mục đích giáo dục và y tế.',
'https://www.rd.usda.gov/programs-services/telecommunications-programs/distance-learning-telemedicine-grants',
'Community Facilities',
'Entities providing education or health care through telecommunications, including schools, libraries, colleges, medical facilities, and consortiums. Must serve rural areas. Must demonstrate need and capacity.',
'Grants up to $1 million (or $3 million for remote Alaska). Covers equipment, software, technical assistance, and instructional programming. Supports broadband transmission, audio/video equipment, and network connectivity. Enables access to specialists and educational resources.',
'1. Form consortium if applicable. 2. Conduct needs assessment. 3. Develop detailed application with network design. 4. Submit during application window. 5. USDA review and scoring. 6. Award notification. 7. Equipment procurement. 8. Installation and training. 9. Begin operations.',
ARRAY['distance learning', 'telemedicine', 'telehealth', 'education', 'healthcare', 'telecommunications', 'rural health', 'technology']);
