INSERT INTO documents (title, description, document_url, document_type, category, language) VALUES
('1710B-1', 'Guide to Federal Financing Bank Loans guaranteed by RUS', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1710b-1.pdf', 'Bulletins', 'Utilities', 'en'),
('1717B-2', 'Guide for Preparing Financial and Statistical Reports for Electric Distribution Borrowers (2/14/02)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1717b-2.pdf', 'Bulletins', 'Utilities', 'en'),
('1717B-3', 'Guide For Preparing Financial and Statistical Reports For Power Supply Borrowers and Electric Distribution Borrowers with Generating Facilities (5/12/06)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1717b-3.pdf', 'Bulletins', 'Utilities', 'en'),
('1717M-2', 'Sale or Transfer of Capital Assets by Electric Borrower (8/3/23)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1717m-2.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-101A', 'Electric System Long-Range Planning Guide (2/16/17)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-101a.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-101B', 'System Planning Guide, Construction Work Plans (12/18/12)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-101b.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-103', 'System planning guide, system mapping guide (4/12/11)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-103.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-104', 'Engineering Economics Computer Workbook Procedure (2/14/19)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-104.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-105', 'Rural Distribution System Voltage Conversion Considerations (5/22/09)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-105.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-106', 'Considerations For Replacing Storm-Damaged Conductors (8/3/10)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-106.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-107', 'Guide for Economic Evaluation of Distribution Transformers (8/9/16)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-107.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-112', 'The Application of Capacitors on Rural Electric Systems (10/4/18)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-112.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-113', 'Voltage Levels on Rural Electric Distribution Systems (5/16/12)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-113.pdf', 'Bulletins', 'Utilities', 'en'),
('1724D-114', 'Voltage Regulator Application on Rural Distribution Systems (7/4/17)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724d-114.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-102', 'Design Guide for Sectionalizing Distribution Lines (10/23/2012)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-102.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-104', 'Reduced Size Neutral Conductors for Overhead Rural Distribution Lines (revised 9/23/1999)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-104.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-150', 'Unguyed Distribution Poles - Strength Requirements (08/14/14)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-150.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-151', 'Mechanical Loading on Distribution Crossarms (2/23/16)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-151.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-152', 'The Mechanics of Overhead Distribution Line Conductors (7/30/03)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-152.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-153', 'Electric Distribution Line Guys and Anchors (4/25/01)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-153.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-154', 'Distribution Conductor Clearances and Span Limitations (7/30/03)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-154.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-200', 'Design Manual for High Voltage Transmission Lines (12/2/15)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-200.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-203', 'Guide for upgrading transmission lines (2/01/16)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-203.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-204', 'Guide Specifications for Steel Single Pole and H-Frame Structures (4/9/19)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-204.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-205', 'Design guide: Embedment depths for concrete and steel poles (5/2/17)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-205.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-206', 'Guide Specification for Prestressed Concrete Poles and Concrete Pole Structures (8/19/16)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-206.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-214', 'Guide Specification for Standard Class Steel Transmission Poles (4/9/19)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-214.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-216', 'Guide Specification for Standard Class Prestressed Concrete Transmission Poles (7/27/16)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-216.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-220', 'Procurement and Application Guide for Non-Ceramic Composite Insulators, Voltage Class 34.5 kV and Above (5/9/17)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-220.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-224', 'Electric Transmission Guide Specifications and Drawings for Steel Pole Construction - 34.5 to 230 kV (5/7/19)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-224.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-226', 'Electric Transmission Guide Specifications and Drawings for Concrete Pole Construction - 34.5 to 230 kV (5/7/19)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-226.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-300', 'Design Guide for Rural Substations (6/07/01)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-300.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-301', 'Guide for the Evaluation of Large Power Transformer Losses (3/4/09)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-301.pdf', 'Bulletins', 'Utilities', 'en'),
('1724E-302', 'Design guide - oil spill prevention and control at substations (1/14/08)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1724e-302.pdf', 'Bulletins', 'Utilities', 'en'),
('1726-601', 'Electric System Construction Policies and Procedures -Interpretations (10/28/13)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1726-601.pdf', 'Bulletins', 'Utilities', 'en'),
('1726C-115', 'Checking sag in a conductor using the return wave method (9/24/98)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1726c-115.pdf', 'Bulletins', 'Utilities', 'en'),
('1726I-602', 'Attachments to Electric Program Standard Contract Forms (2/19/04)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1726i-602.pdf', 'Bulletins', 'Utilities', 'en'),
('1728F-700', 'Specification for Wood Poles, Stubs and Anchor Logs (4/18/22)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1728f-700-0.pdf', 'Bulletins', 'Utilities', 'en'),
('1728F-800', 'Assembly Unit Numbers and Standard Format (10/16/24)', 'https://www.rd.usda.gov/media/file/download/1728f-800-101624.pdf', 'Bulletins', 'Utilities', 'en'),
('1728F-803', 'Specifications and Drawings for 24.9/14.4 kV Line Construction (12/15/98)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1728f-803.pdf', 'Bulletins', 'Utilities', 'en'),
('1728F-803 Notice', 'Compliance with Bulletin 50-5 or 1728F-803', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1728f-803-notice.pdf', 'Bulletins', 'Utilities', 'en'),
('1728F-804', 'Specifications and Drawings for 12.5/7.2 kV Line Construction (4/1/05)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1728f-804.pdf', 'Bulletins', 'Utilities', 'en'),
('1728F-806', 'Specifications and Drawings for Underground Electric Distribution (10/11/18)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1728f-806.pdf', 'Bulletins', 'Utilities', 'en'),
('1728F-810', 'Electric Transmission Specifications and Drawings, 34.5kV Through 6gkV (4/9/1999)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1728f-810.pdf', 'Bulletins', 'Utilities', 'en'),
('1728F-811', 'Electric Transmission Specifications and Drawings, 115kV Through230kV (4/9/1999)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1728f-811.pdf', 'Bulletins', 'Utilities', 'en'),
('1730-1', 'Electric System Operation and Maintenance (O and M) (9/23/16)', 'https://www.rd.usda.gov/media/file/download/uep-bulletin-1730-1.pdf', 'Bulletins', 'Utilities', 'en');